// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARhdNIPtW-LwbvFEJ4yYIzX4V5r-EjDfw',
    appId: '1:1038044321819:web:c1d1a7eac01ad577eb40be',
    messagingSenderId: '1038044321819',
    projectId: 'todo-f9370',
    authDomain: 'todo-f9370.firebaseapp.com',
    storageBucket: 'todo-f9370.appspot.com',
    measurementId: 'G-HQMTTT3SL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2teCxG1NF-oealO6PskEI0OAIFdw-rnQ',
    appId: '1:1038044321819:android:05a4327d78cdbb0deb40be',
    messagingSenderId: '1038044321819',
    projectId: 'todo-f9370',
    storageBucket: 'todo-f9370.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS1aqR3AnsymWyFNhhXD4Uyvxyub7rTFc',
    appId: '1:1038044321819:ios:4e7817fb4b5ecc2feb40be',
    messagingSenderId: '1038044321819',
    projectId: 'todo-f9370',
    storageBucket: 'todo-f9370.appspot.com',
    iosClientId: '1038044321819-f32m2iofiqbvaov94bsjjs20tc8dfic4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS1aqR3AnsymWyFNhhXD4Uyvxyub7rTFc',
    appId: '1:1038044321819:ios:4e7817fb4b5ecc2feb40be',
    messagingSenderId: '1038044321819',
    projectId: 'todo-f9370',
    storageBucket: 'todo-f9370.appspot.com',
    iosClientId: '1038044321819-f32m2iofiqbvaov94bsjjs20tc8dfic4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARhdNIPtW-LwbvFEJ4yYIzX4V5r-EjDfw',
    appId: '1:1038044321819:web:a09f5f959a267473eb40be',
    messagingSenderId: '1038044321819',
    projectId: 'todo-f9370',
    authDomain: 'todo-f9370.firebaseapp.com',
    storageBucket: 'todo-f9370.appspot.com',
    measurementId: 'G-M87FW8C0HK',
  );
}
